"""empty message

Revision ID: 268082eeb4a9
Revises: 581d11442d29
Create Date: 2021-03-05 03:17:48.112515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268082eeb4a9'
down_revision = '581d11442d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('isTradeFair', sa.Boolean(), nullable=True))
    op.drop_column('entry', 'simulation_successfull')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('simulation_successfull', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('entry', 'isTradeFair')
    # ### end Alembic commands ###
