"""empty message

Revision ID: 38ebb778de24
Revises: 068492e62491
Create Date: 2021-02-24 20:53:45.210681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ebb778de24'
down_revision = '068492e62491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('auth_user', sa.Column('first_name', sa.String(length=30), nullable=True))
    # op.add_column('auth_user', sa.Column('last_name', sa.String(length=30), nullable=True))
    # op.add_column('auth_user', sa.Column('username', sa.String(length=80), nullable=False))
    # op.alter_column('auth_user', 'password',
    #            existing_type=sa.VARCHAR(length=192),
    #            nullable=True)
    # op.create_unique_constraint(None, 'auth_user', ['username'])
    # op.drop_column('auth_user', 'status')
    # op.drop_column('auth_user', 'role')
    # op.drop_column('auth_user', 'name')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('auth_user', sa.Column('role', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('auth_user', sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'auth_user', type_='unique')
    op.alter_column('auth_user', 'password',
               existing_type=sa.VARCHAR(length=192),
               nullable=False)
    op.drop_column('auth_user', 'username')
    op.drop_column('auth_user', 'last_name')
    op.drop_column('auth_user', 'first_name')
    # ### end Alembic commands ###
