"""empty message

Revision ID: c6eb46eb0d5f
Revises: cd8ee9c86836
Create Date: 2021-03-05 02:40:44.329014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6eb46eb0d5f'
down_revision = 'cd8ee9c86836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('simulation_succesfull', sa.Boolean(), nullable=True))
    op.drop_column('entry', 'simulation_succesful')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('simulation_succesful', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('entry', 'simulation_succesfull')
    # ### end Alembic commands ###
